---
title: "Exercise 3 - Beamer and equations"
author: "Gerko Vink"
date: "Markup Languages and Reproducible Programming in Statistics"
output: 
   html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: false
---

<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 18px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 18px;
}
h2 { /* Header 2 */
    font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>


---

Dear all, 

This week we will learn how to use $\LaTeX$ to create presentations and we will explore how to use $\LaTeX$ for mathematical notation. 

Let's start. 

Gerko

---

# Presentations with beamer
We use the `beamer` package to create presentations with `tex`. If all is well, you should now be able to create and compile your own `tex` documents (if not, please ask me for help!). Therefore I refer you to [this page](http://userpages.umbc.edu/~rostamia/beamer/) and to the `Beamer_Userguide.pdf` file on [this week's course page](https://www.gerkovink.com/markup/#week-3). For the more tech-savvy users among you, [this](http://www.math-linux.com/latex-26/article/how-to-make-a-presentation-with-latex-introduction-to-beamer) discusses fancy stuff with `beamer`. You can simply ignore the part about `linux` and focus on the `tex` code. 

---

## `beamer` themes
The [beamer theme matrix](https://www.hartwork.org/beamer-theme-matrix/) gives you an overview of the aesthetics of combinations between default beamer themes and standard color themes. Utrecht University also has a `beamer` theme (although unofficial), which uses the UU colors (this week's course page). Let's say that it is rather yellow and leave it at that. Still, many people use it and it is a well-developed style. 

---



---

# Exercises
1. Study [this page](http://userpages.umbc.edu/~rostamia/beamer/) to get yourself acquainted with beamer
2. Study the `AMS example file.pdf` and `AMS example file.tex` to get yourself acquainted with mathematical notation in `tex`. 
3. Recreate the example presentation file `beamer_exercise.pdf` with `beamer` in $\LaTeX$. 

---

Add your solution as a pull request to [the course GitHub page](https://github.com/gerkovink/markup2020). 

---
