# GenAI rules {.unnumbered}
You may use generative AI in this course if and only if you read the below paragraphs.

## Copyright and intellectual property

::: callout-tip
# Do you know your input rights?
At Methodology and Statistics we hold ethics, honesty, and the values of open science in the highest regard. These principles are the backbone of our academic community and guide our education as well as our pursuit of knowledge.

Now that AI tools become more advanced and widespread, it is crucial to uphold these values. While much focus has been on the output of AI tools, I want to bring attention to a different concern: the unjust use of what we input into these tools.

Many of us interact with AI in what feels like the privacy of our own devices. This perceived privacy can create a false sense of security, leading some to input information that was not theirs to share or should have remained confidential. To safeguard our integrity and respect intellectual property rights, we must be cautious about what we share with AI tools. Specifically,

- Do not input assignments, course materials, scientific manuscripts or any other work without explicit permission from the owners.
- Avoid using AI tools to process, summarize, grade or evaluate each other's work unless you have the author’s consent.

By following these guidelines, we protect and respect both the creative efforts and the intellectual property in our community.
:::

## What about this course?
The materials in this course are generated by M&S teaching staff, who hold the copyright. The intellectual property belongs to Utrecht University. Images are either self-generated, directly linked, or generated with AI tools. That said, there is no information in these that exceeds legal use of copyright materials in academic settings, or that is not publicly available or should not be part of the public domain. 

::: {.callout-warning}
You **may use** any and all content in this course - including staff names - and submit it as input to generative AI tools, with the following **exception**:

- You must ensure that the content is not used for further training of the model
:::

## Our advice
Generative AI can be a great assistant in the generating structured language. Most of the markup and programming languages that we will consider in this course are extremely structured and generative AI can be of great help. Mastering a new language, however, requires practice and becoming dependent on genAI will hinder your progression in the long run. Therefore we advice you to also interact with your instructors, peers and other resources around the web, as it will transform you from a leecher into a seeder. Or in educational terms: if you can explain to others what and why you are doing, you have transformed from student to master. 

