{
  "hash": "fc3290cd54f761b406b367a382b43cd2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"My Reproducible Manuscript\"\nauthor: \"Adam Maghout\"\nformat:\n  pdf: default\nbibliography: references.bib\n---\n\n\n\n# Purpose of the project\n\nThe project presented here is a reproduction of work by @boulesteixIntroductionStatisticalSimulations2020, done for the purpose of an exercise of the Markup Languages and Reproducible Programming in Statistics course offered by Utrecht University. The code used here was provided by the original researchers in pdf form then converted into workable R code by Gerko Vink and Hanne Oberman. Likewise, the data used was also extracted from the website of the [Centers for Disease Control and Prevention (CDC)](https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?Begi-nYear=2015) by these two researchers. Presenting the findings and formatting this document were done by Adam Maghout.\n\n# Libraries\n\nThe required libraries for this project are given below:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Hmisc)\nlibrary(mice)\nlibrary(tidyverse)\n```\n:::\n\n\n\n# Data\n\nData from 5092 subjects in the 2015–2016 National Health and Nutrition Examination Survey (NHANES) are used to obtain an estimate of the effect of HbA1c on systolic blood pressure, while adjusting for age, gender and body mass index (BMI). Since the NHANES website provides the data in several datasets, we must first select only the variables of interest for our analysis. These are:\n\n-   RIAGENDR - Gender\n-   RIDAGEYR - Age in years at screening\n-   BPXSY1 - Systolic: Blood pres (1st rdg) mm Hg\n-   BMXBMI - Body Mass Index (kg/m\\*\\*2)\n-   LBDTCSI - Total Cholesterol (mmol/L)\n-   LBXGH - Glycohemoglobin (\\%)\n\nInformation on other variables in the datasets is given on the [NHANES website](https://wwwn.cdc.gov/nchs/nhanes/) but also in the column descriptions in the datasets.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read data:\nd1 <- sasxport.get(\"../data/DEMO_I.xpt\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProcessing SAS dataset DEMO_I \t ..\n```\n\n\n:::\n\n```{.r .cell-code}\nd2 <- sasxport.get(\"../data/BPX_I.xpt\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProcessing SAS dataset BPX_I \t ..\n```\n\n\n:::\n\n```{.r .cell-code}\nd3 <- sasxport.get(\"../data/BMX_I.xpt\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProcessing SAS dataset BMX_I \t ..\n```\n\n\n:::\n\n```{.r .cell-code}\nd4 <- sasxport.get(\"../data/GHB_I.xpt\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProcessing SAS dataset GHB_I \t ..\n```\n\n\n:::\n\n```{.r .cell-code}\nd5 <- sasxport.get(\"../data/TCHOL_I.xpt\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProcessing SAS dataset TCHOL_I \t ..\n```\n\n\n:::\n\n```{.r .cell-code}\n# Filter for variables of interest\nd1.t <- subset(d1,select=c(\"seqn\",\"riagendr\",\"ridageyr\"))\nd2.t <- subset(d2,select=c(\"seqn\",\"bpxsy1\"))\nd3.t <- subset(d3,select=c(\"seqn\",\"bmxbmi\"))\nd4.t <- subset(d4,select=c(\"seqn\",\"lbxgh\"))\nd5.t <- subset(d5,select=c(\"seqn\",\"lbdtcsi\"))\nd <- merge(d1.t,d2.t)\nd <- merge(d,d3.t)\nd <- merge(d,d4.t)\nd <- merge(d,d5.t)\n\n# Rename variables:\nd$age <- d$ridageyr\nd$sex <- d$riagendr\nd$bp <- d$bpxsy1\nd$bmi <- d$bmxbmi\nd$HbA1C <- d$lbxgh\nd$chol <- d$lbdtcsi\nd$age[d$age<18] <- NA\n\n# select complete cases:\ndc <- cc(subset(d,select=c(\"age\",\"sex\",\"bmi\",\"HbA1C\",\"bp\")))\n```\n:::\n\n\n\n# Baseline Model\n\nThe effect of HbA1c on systolic blood pressure is measured using a linear model. Initially, this model is given whilst adjusting for age and sex. Then, BMI is also used as an adjusting factor:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1\nsummary(lm(bp ~ HbA1C + age + as.factor(sex), data=dc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bp ~ HbA1C + age + as.factor(sex), data = dc)\n\nResiduals:\nSystolic: Blood pres (1st rdg) mm Hg \n    Min      1Q  Median      3Q     Max \n-49.887 -10.509  -1.378   8.491 107.583 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     98.75149    1.21418  81.332  < 2e-16 ***\nHbA1C            1.12638    0.20291   5.551 2.98e-08 ***\nage              0.44486    0.01284  34.648  < 2e-16 ***\nas.factor(sex)2 -3.24792    0.45164  -7.191 7.34e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.1 on 5088 degrees of freedom\nMultiple R-squared:  0.2305,\tAdjusted R-squared:   0.23 \nF-statistic:   508 on 3 and 5088 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(lm(bp ~ HbA1C + age + as.factor(sex), data=dc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     2.5 %      97.5 %\n(Intercept)     96.3711755 101.1317982\nHbA1C            0.7285836   1.5241825\nage              0.4196932   0.4700355\nas.factor(sex)2 -4.1333281  -2.3625106\n```\n\n\n:::\n:::\n\n\n\nIn this first model, we find that HbA1c increases systolic blood pressure by 1.13 mmHg (95\\% CI 0.73 to 1.52) per unit increase in HbA1c. This is given under the coefficients in the summary.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 2\nsummary(lm(bp ~ HbA1C + bmi + age + as.factor(sex), data=dc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bp ~ HbA1C + bmi + age + as.factor(sex), data = dc)\n\nResiduals:\nSystolic: Blood pres (1st rdg) mm Hg \n    Min      1Q  Median      3Q     Max \n-51.068 -10.251  -1.504   8.264 107.410 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     92.65583    1.39320  66.506  < 2e-16 ***\nHbA1C            0.75177    0.20596   3.650 0.000265 ***\nbmi              0.28632    0.03282   8.724  < 2e-16 ***\nage              0.44586    0.01275  34.979  < 2e-16 ***\nas.factor(sex)2 -3.63115    0.45049  -8.060  9.4e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.98 on 5087 degrees of freedom\nMultiple R-squared:  0.2418,\tAdjusted R-squared:  0.2412 \nF-statistic: 405.7 on 4 and 5087 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(lm(bp ~ HbA1C + bmi + age + as.factor(sex), data=dc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     2.5 %     97.5 %\n(Intercept)     89.9245592 95.3871089\nHbA1C            0.3479966  1.1555348\nbmi              0.2219815  0.3506673\nage              0.4208695  0.4708464\nas.factor(sex)2 -4.5143014 -2.7479929\n```\n\n\n:::\n:::\n\n\n\nIn this second model, adjusting for BMI, we find that HbA1c instead increases systolic blood pressure by  0.75 mmHg (95\\% CI 0.35 to 1.16) per unit increase in HbA1c.\n\n# Added Measurement error\n\nMeasurement error is added to the HbA1c and BMI data by setting a proportion of the observed variance in both variables to be due to measurement error. This proportion ranges from 0 to 50\\%, yielding a total of $6*6=30$ scenarios across both variables. This process is repeated 1 000 times for each scenario to obtain measures of spread.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulation of measurement error:\n# Baseline increase\nref <- lm(bp ~ HbA1C + bmi + age + as.factor(sex), data=dc)$coef[2]\n\nn.sim <- 1e3 # Number of iterations\n\n# exp = exposure variable; conf = confounding variable\nperc.me.exp <- seq(0,.5,.1) # Proportion of measurement error variance for the HbA1c\nperc.me.conf<- seq(0,.5,.1) # Proportion of measurement error variance for the BMI\nscenarios <- expand.grid(perc.me.exp,perc.me.conf) # 36 scenarios\n\n# Variances without measurement error\nvar.exp <- var(dc$HbA1C)\nvar.conf <- var(dc$bmi)\n\nn <- dim(dc)[1] # Number of observations\n\nbeta.hat <- matrix(ncol=dim(scenarios)[1], nrow=n.sim) # Initialise results matrix\n\n# Simulate measurement error\nfor (k in 1:n.sim){\n  # print(k) # Can be used for tracking\n  set.seed(k)\n  for (i in 1:dim(scenarios)[1]){ # 1 000 iterations\n    # Compute variances\n    var.me.exp <- var.exp*scenarios[i,1]/(1-scenarios[i,1])\n    var.me.conf <- var.conf*scenarios[i,2]/(1-scenarios[i,2])\n    \n    # Add meaurement error\n    dc$HbA1C.me <- dc$HbA1C + rnorm(dim(dc)[1], 0, sqrt(var.me.exp) )\n    dc$bmi.me <- dc$bmi + rnorm(dim(dc)[1], 0, sqrt(var.me.conf) )\n    \n    # Obtain desired coefficient\n    beta.hat[k,i] <- lm(bp ~ HbA1C.me + age + bmi.me + as.factor(sex), data=dc)$coef[2]\n  }}\n```\n:::\n\n\n\n# Figure\n\nGiven the results from the previous section, figure 2 is obtained as follows:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create figure:\ntot.mat <- cbind(100*scenarios,apply(beta.hat,2,mean))\ncolnames(tot.mat) <- c(\"me.exp\",\"me.conf\",\"estimate\")\nFIGURE <- ggplot(tot.mat, aes(me.exp, me.conf)) +\n  geom_tile(color=\"white\",aes(fill = estimate)) +\n  geom_text(aes(label = round(estimate, 2))) +\n  scale_fill_gradient2(low=\"#D55E00\",mid=\"white\",high = \"#56B4E9\", midpoint=ref) +\n  labs(x=paste(\"% of total variance of HbA1c due to measurement error\"),\n       y=paste(\"% of total variance of BMI due to measurement error\")) +\n  coord_equal()+\n  scale_y_continuous(breaks=unique(tot.mat[,1]))+\n  scale_x_continuous(breaks=unique(tot.mat[,1]))+\n  theme(panel.background = element_rect(fill='white', colour='grey'),\n        plot.title=element_text(hjust=0),\n        axis.ticks=element_blank(),\n        axis.title=element_text(size=12),\n        axis.text=element_text(size=10),\n        legend.title=element_text(size=12),\n        legend.text=element_text(size=10))\n\nFIGURE # display the figure\n```\n\n::: {.cell-output-display}\n![](my-reproducible-manuscript_files/figure-pdf/figure-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# Save the figure (optional)\n# savePlot(\"Figure_STRATOS.tif\", type=\"tif\")\n```\n:::\n\n\n\nThe relation between HbA1c and systolic blood pressure was attenuated when measurement error was added to HbA1c, but not when measurement error was added to BMI. The association became stronger as measurement error was added solely to the confounding variable BMI. The reason for this effect is that, with increasing levels of measurement error on BMI, adjustment for the confounding due to BMI becomes less efficient and the effect estimate gets closer to the unadjusted estimate (1.13 mmHg). Due to measurement error, a type of residual confounding is introduced. In the case of measurement error on HbA1c as well as BMI, both phenomena play a role and may cancel each other out.\n\n\n\n{{< pagebreak >}}\n\n\n\n\n# Bibliography\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}