---
title: "Exercise 8 - GitHub Pages and Shiny"
author: "Gerko Vink"
date: "Markup Languages and Reproducible Programming in Statistics"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: true
---

<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 8px;
}
h1.title {
  font-size: 24px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 18px;
}
h2 { /* Header 2 */
    font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>

---

Dear all, 

This week we'll lear how to let `GitHub` render your html files, how to host a free, easily maintainable personal web page and how to deploy 'simple' webapps. 

Best, 

Gerko

---

# `GitHub Pages` with `Jekyll`

[`GitHub Pages`](https://pages.github.com) is a facility to host websites directly from your GitHub repositories. The content can be served amongst other formats as standard `html` or as `markdown` and `GitHub Pages` will take care of rendering the content to the device. This makes it very straightforward for developers to publish and maintain personal websites or project websites directly from the `GitHub` repository. Moreover, when `GitHub` project repositories contain `html` files, by default, these files will be shown as raw user content. When a repository is published as a `GitHub Page`, the `html` or `markdown` content is automatically rendered and served as a compiled document - please note that `rmarkdown` specific facilities, such as rendering `R`-code, can only be compiled from within `R`-studio. 

The [`GitHub Pages`](https://pages.github.com) site walks you through creating personal and project sites from scratch. The back-end of GitHub Pages is [`Jekyll`](https://jekyllrb.com), an open-source static site generator. Jekyll allows for advanced customization and styling through [themes](http://jekyllthemes.org). The standard `Jekyll` functionality and theming that is offered by `GitHub` will serve most users fine. However, [`Jekyll`](https://jekyllrb.com) is written in [`Ruby`](https://www.ruby-lang.org/en/) and customizing your websites beyond the standard functionality offerd by `GitHub` requires some effort in coding `Ruby`. Both `GitHub` and `Jekyll` walk you through many of these codes executions in step-by-step instructions. Have a look at [this link](https://github.com/collections/github-pages-examples) to view some examples of great GitHub pages.

To learn about using `GitHub Pages`, I suggest you take the following steps

1. Go through [`this link`](https://pages.github.com) to create a personal website (a `username.github.io` page)
2. Then create a project website - you can use the [`same link`](https://pages.github.com)
3. Use the [theme chooser](https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site-with-the-jekyll-theme-chooser/) to customize your page's appearence

For more advanced customizibility, have a look at the following links

- [Adding a non-default `Jekyll` theme](https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/) ***[requires some `Ruby` coding]***
- [Setting up your `GitHub Pages` site locally with `Jekyll`](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/), which comes in very handy if you like to code, test and develop your site in an offline clone. ***[requires some `Ruby` coding]***
- [Using a custom domain with `GitHub Pages`](https://help.github.com/articles/using-a-custom-domain-with-github-pages/)

---

# Alternative to `Jekyll`
I personally prefer [`hugo`](https://gohugo.io) over [`Jekyll`](https://jekyllrb.com) for personal webpages. `hugo` is even more minimalistic to maintain as it is fully `markdown` and `yaml` (e.g. `rmarkdown`'s header is `yaml`) based. Best of all, `hugo` integrates seamlessly into the git workflow. Use the [`hugo quickstart`](https://gohugo.io/getting-started/quick-start) to set up your first `hugo` page locally.

---

# `Shiny` web apps
[`Shiny`](http://shiny.rstudio.com) is an `R` package that makes it easy to build interactive web apps straight from R. You can host standalone apps on a webpage or embed them in `rmarkdown` documents and dashboards.
If you like to browse around in the wonderful world that is `Shiny`, [this link](http://shiny.rstudio.com/gallery/) provides you with a great overview. 

To publish your `Shiny` app in a simple manner, there are two classes of options: one class that requires the user to have `Shiny` installed on their machine (e.g. on `GitHub`) and one class that does not require the user to have `Shiny` installed (e.g. [`shinyapps.io`](http://www.shinyapps.io)). Of course, there are more options to deploy `Shiny` web apps, but they require you to host your own `Shiny` server on your personal domain. 

To create a `Shiny` app from `R`, you need to provide two documents: a user-interface (`ui`) component and a `server` instruction set. With the `Shiny` package in `R`, the `ui` and `server` components are combined and the corresponding `html` code is generated and compiled for you. Normally, this would require you to have advanced knowledge and skills about servers, interfaces and `html`, but with `Shiny` this process is extremely simplified into an `R` programming scenario. 

To learn about using `Shiny` to create web-apps, I suggest you take the following steps

1. `RStudio` offers `a quiz` that tests your `R` proficiency yo see whether you are ready for `Shiny`. I suggest you take it and, if you do not know all the answers, use that knowledge later on to debug problems with `Shiny`. 
2. Go through [this $2 \frac{1}{2}$ hour tutorial](http://shiny.rstudio.com/tutorial/). If you prefer a written tutorial, I suggest you take [this one](http://shiny.rstudio.com/tutorial/written-tutorial/lesson1/). However, the written tutorial is less comprehensive than the video tutorial. For the most comprehensive overview, see [this book under development](https://mastering-shiny.org). 
3. Create a [`shinyapps.io`](http://www.shinyapps.io) account - a free one will do
4. Follow the steps given by `shinyapps.io` to connect your `RStudio` installation to `shinyapps` throught the `rsconnect` package in `R`
5. Create a `Shiny` app and publish it to [`shinyapps.io`](http://www.shinyapps.io)

---

# Exercise

Do the following before January 14, 2019:

1. Create a personal `Page` on `GitHub` that showcases you. Pay attention to e.g.
  - who are you
  - what do you do (e.g. expertise, service, product)
  - where people may find you (`GitHub`, Company page, facebook, G+, twitter, etc.)
  - accomplishments/publications/qualifications/skills etc.
  - a detailed curriculum vitae
2. Publish a `Shiny` app. If your app is subject to sensitive data or non-disclosure, I suggest you use a private `GitHub` repo to host your app. Otherwise, use `shinyapps.io`. 

---

I've set the deadline to January 15th to allow you to work towards the final deliveries for this course such that you can avoid duplicate work. Do not hesitate to ask for help. 

All the best, 

Gerko


